force-app/main/default/objects/Field_History__c/Field_History__c.object-meta.xml
<CustomObject>
    <label>Field History</label>
    <nameField>
        <displayFormat>FH-{0000}</displayFormat>
        <label>Field History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History__c/fields/Tracked_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Field_API__c</fullName>
    <description>API name of the tracked field</description>
    <label>Tracked Field API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Tracker_Field__mdt/Field_Tracker_Field__mdt.object-meta.xml
<CustomObject>
    <label>Field Tracker Field</label>
    <pluralLabel>Field Tracker Fields</pluralLabel>
</CustomObject>

force-app/main/default/classes/FieldTrackerServiceTest.cls
@IsTest
class FieldTrackerServiceTest {
	@TestSetup
	static void makeData() {
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < 200; i++) {
			Account acc = new Account(
				Name = 'Account i' + i,
				BillingCountry = 'United States'
			);
			accounts.add(acc);
		}

		insert accounts;
	}

	@IsTest
	static void testAccountFTS() {
		System.assert(
			[SELECT Id FROM Field_Tracker_Field__mdt]?.size() > 0,
			'No Custom Metadata records found in Field Tracker Object and Field Tracker Field, please add to pass tests'
		);
	}

	@IsTest
	static void testAccountFTSUpdate() {
		Account[] accounts = [SELECT id FROM Account];
		for (Account acc : accounts) {
			acc.BillingCountry = 'India';
		}

		update accounts;

		System.assert(
			[
				SELECT Id
				FROM Field_History__c
				WHERE Tracked_Field_API__c = 'BillingCountry'
			]
			?.size() > 0
		);
	}
}