force-app/main/default/objects/Field_History__c/Field_History__c.object-meta.xml
<CustomObject>
    <label>Field History</label>
    <nameField>
        <displayFormat>FH-{0000}</displayFormat>
        <label>Field History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Tracked_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Field_API__c</fullName>
    <description>API name of the tracked field</description>
    <label>Tracked Field API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Tracked_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Record_Id__c</fullName>
    <label>Tracked Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
class AccountTriggerTest {
	@TestSetup
	static void makeData() {
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < 200; i++) {
			Account acc = new Account(
				Name = 'Account FTS ' + i,
				BillingCountry = 'United States'
			);
			accounts.add(acc);
		}

		insert accounts;
	}

	@IsTest
	static void testAfterInsertHistory() {
		Set<Id> accountIds = new Map<Id, Account>(
				[SELECT Id FROM Account WHERE Name LIKE 'Account FTS %']
			)
			.keySet();

		Test.startTest();
		System.assertEquals(
			[
					SELECT Id
					FROM Field_History__c
					WHERE
						Tracked_Field_API__c = 'BillingCountry'
						AND Tracked_Record_Id__c IN :accountIds
						AND Old_Value__c = NULL
				]
				?.size(),
			200,
			'Field history records not found'
		);
		Test.stopTest();
	}

	@IsTest
	static void testAfterUpdateHistory() {
		Account[] accounts = [
			SELECT Id
			FROM Account
			WHERE Name LIKE 'Account FTS %'
		];

		Set<Id> accountIds = new Map<Id, Account>(accounts).keySet();

		for (Account acc : accounts) {
			acc.BillingCountry = 'India';
			acc.Description = 'Test Description';
		}

		update accounts;

		Test.startTest();

		System.assertEquals(
			[
					SELECT Id
					FROM Field_History__c
					WHERE
						Tracked_Field_API__c = 'BillingCountry'
						AND Tracked_Record_Id__c IN :accountIds
						AND Old_Value__c = 'United States'
				]
				?.size(),
			200,
			'Field history records not found'
		);
		System.assertEquals(
			[
					SELECT Id
					FROM Field_History__c
					WHERE
						Tracked_Field_API__c = 'Description'
						AND Tracked_Record_Id__c IN :accountIds
				]
				?.size(),
			200,
			'Field history records not found'
		);

		Test.stopTest();
	}
}