force-app/main/default/objects/Field_History__c/Field_History__c.object-meta.xml
<CustomObject>
    <label>Field History</label>
    <nameField>
        <displayFormat>FH-{0000}</displayFormat>
        <label>Field History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_History__c/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>Label of the tracked field</description>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Tracked_Field_API__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Field_API__c</fullName>
    <description>API name of the tracked field</description>
    <label>Tracked Field API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Tracked_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Field_Label__c</fullName>
    <description>Label of the tracked field</description>
    <label>Tracked Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Tracked_Object__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Object__c</fullName>
    <description>Name of the object</description>
    <label>Tracked Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_History__c/fields/Tracked_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Record_Id__c</fullName>
    <label>Tracked Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Tracker_Field__mdt/Field_Tracker_Field__mdt.object-meta.xml
<CustomObject>
    <label>Field Tracker Field</label>
    <pluralLabel>Field Tracker Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Tracker_Field__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Field to be tracked</description>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Tracker_Field__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field (Label)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Tracker_Field__mdt/fields/Field_Tracker_Object__c.field-meta.xml
<CustomField>
    <fullName>Field_Tracker_Object__c</fullName>
    <label>Field Tracker Object</label>
    <referenceTo>Field_Tracker_Object__mdt</referenceTo>
    <relationshipLabel>Field Tracker Fields</relationshipLabel>
    <relationshipName>Field_Tracker_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Field_Tracker_Object__mdt/Field_Tracker_Object__mdt.object-meta.xml
<CustomObject>
    <label>Field Tracker Object</label>
    <pluralLabel>Field Tracker Objects</pluralLabel>
</CustomObject>

force-app/main/default/classes/FieldTrackerService.cls
/* 
    Singleton Class implements the custom field history
    tracking dynamically through custom metadata configuration
*/
public without sharing class FieldTrackerService {
	// Static members
	private static FieldTrackerService instance;

	public static FieldTrackerService getInstance(String objectName) {
		if (instance == null) {
			instance = new FieldTrackerService(objectName);
		}
		return instance;
	}

	// instance members
	private String objectName;
	private Set<String> fields;
	private List<Field_Tracker_Field__mdt> trackedFields;
	private Field_Tracker_Object__mdt ftObject;

	private FieldTrackerService(String objectName) {
		this.objectName = objectName;

		ftObject = Field_Tracker_Object__mdt.getInstance(objectName);

		if (ftObject.Is_Active__c) {
			trackedFields = [
				SELECT Field__c, Field_Label__c, Is_Long_Text__c
				FROM Field_Tracker_Field__mdt
				WHERE
					Field_Tracker_Object__c = :ftObject.Id
					AND Is_Active__c = TRUE
			];
			fields = Schema.getGlobalDescribe()
				.get(objectName)
				.getDescribe()
				.fields.getMap()
				.keySet();
		}
	}

	// OldMap should be null in case of Insert trigger.
	public void saveFieldHistories(
		List<SObject> records,
		Map<Id, SObject> oldMap
	) {
		if (
			ftObject != null &&
			ftObject.Is_Active__c &&
			trackedFields != null &&
			!trackedFields.isEmpty()
		) {
			List<Field_History__c> fieldHistories = new List<Field_History__c>();
			Boolean isNew = oldMap == null;
			for (SObject record : records) {
				SObject oldRecord = oldMap?.get(record.Id);
				for (Field_Tracker_Field__mdt trackedField : trackedFields) {
					if (
						String.isNotBlank(trackedField.Field__c) &&
						fields.contains(trackedField.Field__c.toLowerCase()) &&
						(isNew && record.get(trackedField.Field__c) != null ||
						!isNew &&
						oldRecord.get(trackedField.Field__c) !=
						record.get(trackedField.Field__c))
					) {
						Field_History__c history = new Field_History__c(
							Tracked_Object__c = objectName,
							Tracked_Field_Label__c = trackedField.Field_Label__c,
							Tracked_Field_API__c = trackedField.Field__c,
							Tracked_Record_Id__c = record.Id
						);

						if (!trackedField.Is_Long_Text__c) {
							history.New_Value__c = String.valueOf(
								record.get(trackedField.Field__c)
							);
							history.Old_Value__c = String.valueOf(
								oldRecord?.get(trackedField.Field__c)
							);
						} else {
							history.New_Value_Long_Text__c = String.valueOf(
								record.get(trackedField.Field__c)
							);
							history.Old_Value_Long_Text__c = String.valueOf(
								oldRecord?.get(trackedField.Field__c)
							);
							history.Is_Long_Text__c = true;
						}
						fieldHistories.add(history);
					}
				}
			}
			insert fieldHistories;
		}
	}
}